[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
cubist_solana_program = "9HCQ6AHFBWWDSz82oThQN6P6dNNrvWFqyEpMhq6gXo3a"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/deploy_wallet_2.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
